spring.application.name=abhirail_eventstream_receiver

spring.kafka.streams.application-id=abhirail-eventstream
# the type of deserializer defined below should be in sync with the data type of "Key" part of the event information
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
# the type of deserializer defined below should be in sync with the data type of "value" part of the event information
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer

